### ISSUE TITLE
can you upgrade this to ios8 style transitions?

### ISSUE THREAD

**Issue by hsavit1** [jonathantribouharet/JTMaterialTransition#1]
would be awesome if i can use this as a navigationController showVIewController transition. Thanks!

**Comment by johnvuko** [comment]
I think you can. Check this http://stackoverflow.com/questions/22884111/how-to-use-uiviewcontrolleranimatedtransitioning-with-uinavigationcontroller.

**Comment by hsavit1** [comment]
this worked. You just have to implement the UINavigationController delegate and the 1 transitioning delegate it conforms to. Then set the return type of that transition to your transition
