### ISSUE TITLE
Animation is different if you use a NavigationController

### ISSUE THREAD

**Issue by WilliamHua** [jonathantribouharet/JTMaterialTransition#2]
The JTMaterialTransition works perfectly if I use a regular ViewController as the presentedViewController.

If I present a NavigationController or a NavigationController that holds a SWRevealViewController (which is a VC Library that allows you to have drawers), the animation isn't as fluid (it looks worse). Is there any quick workaround to this?

**Comment by johnvuko** [comment]
I try to with a UINavigationController and it works well. I think your problem is your navigation controller view don't have a background color, so the animation is a little strange. Try to set it and come back.

**Comment by WilliamHua** [comment]
You're right thanks so much! Sorry for the confusion, I didn't know that UINavigationController had a background color.

**Comment by johnvuko** [comment]
UINavigationController inherits from UIViewController. I add a notice in the README, I think you're not the only one to have this problem.
