### ISSUE TITLE
Transitioning into View

### ISSUE THREAD

**Issue by EralpB** [jonathantribouharet/JTMaterialTransition#4]
Hello, what would be the best way to transition into the view itself, not just to a color?

Imagine opening the camera view for taking a photo, or a complex view with a lot of controls. Transitioning into a solid color doesn't feel right.

Thank you, if you show me a direction I would like to submit a pull request.

**Comment by johnvuko** [comment]
Did you try to set `clearColor` or a `whiteColor` with alpha?
