### ISSUE TITLE
Do we need to use "presentViewController" ?

### ISSUE THREAD

**Issue by hsavit1** [jonathantribouharet/JTMaterialTransition#5]
I am having difficulty using "showViewController"

Does this only work for modal transitions?

**Comment by hsavit1** [comment]
What im really getting at is... is there any way to leverage this class to be used with UINavigationControllerDelegate ? So that we can do push / pop animations ?

**Comment by johnvuko** [comment]
I think you can #1 . Check this http://stackoverflow.com/questions/22884111/how-to-use-uiviewcontrolleranimatedtransitioning-with-uinavigationcontroller.
