### ISSUE TITLE
Hi！The viewController life cycle abnormality

### ISSUE THREAD

**Issue by xhzengAIB** [jonathantribouharet/JTMaterialTransition#8]
Hi! @jonathantribouharet 

I use the library on my app.

But the viewController not call prefersStatusBarHidden / preferredStatusBarStyle / ViewAppears / ViewDisAppear Methods.

I think the animator don't manage toViewController and formViewController Life Cycle.

But i have no idea due with problem.

Hope you help me.

Jack

**Comment by johnvuko** [comment]
I use `UIViewControllerAnimatedTransitioning` protocol, so it's not on me if you have a problem with this, sorry but I'm sure `ViewAppears` and others are called because I use it in my projects.

**Comment by xhzengAIB** [comment]
@jonathantribouharet 
you should need add this line https://github.com/jonathantribouharet/JTMaterialTransition/blob/master/Example/Example/ViewController.m#L22

``` objc
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
}
```

The `
viewWillAppear
` method called, but when close secondViewController page, this methods not called.

I delete https://github.com/jonathantribouharet/JTMaterialTransition/blob/master/Example/Example/ViewController.m#L53 and
https://github.com/jonathantribouharet/JTMaterialTransition/blob/master/Example/Example/ViewController.m#L54 line.
don't use UIViewControllerAnimatedTransitioning

The `viewWillAppear` method called.

I'm sure this is a bug.

Jack

**Comment by johnvuko** [comment]
I just add in the Example project to test:

```
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    NSLog(@"viewWillAppear");
}
```

and it works, the log show "viewWillAppear" each time the view appear, so you have a problem in your project.

**Comment by xhzengAIB** [comment]
@jonathantribouharet 

I testing in your Example, not in my project.

**Comment by xhzengAIB** [comment]
This bug may be is iOS SDK bug.

**Comment by xhzengAIB** [comment]
@jonathantribouharet 
I pull request commit to your library, you can see the bug.

**Comment by johnvuko** [comment]
I'm sorry but your code can't work, `viewWillAppearCount` need to be a static variable else it's set to 0 each time the view appear. And the library works because the AlertView is shown.

**Comment by xhzengAIB** [comment]
You may need to be in close SecondViewController, to test the viewWillAppear call number.

**Comment by xhzengAIB** [comment]
If Example use UIViewControllerAnimatedTransitioning for JTMaterialTransition.
When you presentViewController to SecondViewController, now close SecondViewController, not called `viewWillAppear` methods.

If Example not use UIViewControllerAnimatedTransitioning,
When you presentViewController to SecondViewController, now close SecondViewController, called `viewWillAppear` methods at any time.
